### PR TITLE
Add LICENSE file.

### LINKED ISSUE #5: Repo missing LICENSE
I am attempting to package this project. However, there is no copy of the MIT LICENSE in the repo. Can a LICENSE file be added and included in the MANIFEST so it is added to tarball?

### PR DESCRIPTION
**Pull request by smarlowucf**
And add LICENSE to MANIFEST.

Fixes #5 

---
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-faker/9)

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
great job, i believe the setup.cfg needs an entry so the wheel command includes it as well

something like https://github.com/pytest-dev/pytest/blob/master/setup.cfg#L13

**Comment by smarlowucf** [comment]
Re-based to add license_files option in tox.ini.

**Comment by RonnyPfannschmidt** [comment]
my understanding is that its supposed to be singular, not plural, its singular in the line i linked,
if this form works as well its fine and we should put a note here in gh else please correct it

**Comment by smarlowucf** [comment]
It appears the file is found separate of the `license_files` addition:

`adding license file "LICENSE" (matched pattern "LICEN[CS]E*")`.

Also, according to [wheel docs](https://wheel.readthedocs.io/en/stable/user_guide.html?highlight=license_file#including-license-files-in-the-generated-wheel-file) the singular version is deprecated.

> There used to be an option called license_file (singular). As of wheel v1.0, this option has been deprecated in favor of the more versatile license_files option.

**Comment by RonnyPfannschmidt** [comment]
thanks for the update, well done :+1:

**Pull request merged**
